### ISSUE TITLE
Create github workflow for deploying docker image

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/projectlive-nf-data#1]
@thomasyu888 We talked about creating a repo for the purpose of deploying the docker image that we set up the cron job for. This is that repo! It has all the pieces to create the docker image from the app repo.

@jaybee84 Is there a specific repo you want to store the docker image at? Is there a specific name you want to call the image?

**Comment by jaybee84** [comment]
It makes sense to store the docker image at : https://hub.docker.com/u/sagebionetworks

Re name: how does `projectlive-nf-cron` sound?

**Comment by thomasyu888** [comment]
I created the repo: https://hub.docker.com/repository/docker/sagebionetworks/projectlive-nf-cron.   I allowed for `sagebot` dockerhub user to have admin permission on the repo.  You can find the credentials on lastpass and set up the github action

**Comment by andrewelamb** [comment]
@thomasyu888 Thanks!

How do we manage tags? I see this:

`tags: sagebionetworks/projectlive-nf-cron:${{ steps.meta.outputs.tags }}`

But I don't understand what it means.

**Comment by andrewelamb** [comment]
@thomasyu888 I'm not seeing any tags [here](https://hub.docker.com/r/sagebionetworks/projectlive-nf-cron/tags).

**Comment by thomasyu888** [comment]
@andrewelamb we have to work on this: https://github.com/Sage-Bionetworks/projectlive-nf-data/pull/2/files.  or... There are multiple ways we can push to the docker repository.   Please see the [Docker section](https://sagebionetworks.jira.com/wiki/spaces/IBC/pages/2222293061/IT+Best+Practices#Sage-Bionetworks-DockerHub).

We can use either method.  The PR I linked in this ticket is the start of one of the methods.

**Comment by andrewelamb** [comment]
@thomasyu888  Is this ready as well?

**Comment by thomasyu888** [comment]
@andrewelamb This is done since we linked up the automated build in dockerhub.
